### ISSUE TITLE
How to use dataset

### ISSUE THREAD

**Issue by Legitao** [AI-nstein/hoppity#1]
Hello,

1. Could you guide me on how to train the "cooked dataset of pairs with a single AST difference" provided by you(i.e. what's the command to run the training on the cooked dataset)?

2. Also, in the readme, you said "run run_main.sh to train on our pre-processed dataset", but it seems there is no run_main.sh file in your codebase.

Thanks,
Tao

**Comment by Legitao** [comment]
For the cooked dataset, the name `cooked-one-diff.gz` indicates its a compressed file, which leads me to unzip it first. But it's actually a tar.gz, so we need to use `tar xzf cooked-one-diff.gz` instead

**Comment by chontipan** [comment]
I also cannot find run_main.sh or how to run training by other ways.

**Comment by elizabethdinella** [comment]
Hi all, 

So sorry for the late response! I now have notifications turned on to follow all issues :) Thank you @Legitao for your help with the tar file. I've updated the README accordingly. 

As for the `run_main.sh` file, I've pushed it to the training folder.
