### ISSUE TITLE
Error when runing the trained model (onediff)

### ISSUE THREAD

**Issue by chontipan** [AI-nstein/hoppity#10]
Hi, I use the trained model (onediff) and got these errors.

![image](https://user-images.githubusercontent.com/9138402/95441164-60db7a80-098c-11eb-9cd4-a247aeb91978.png)

my eval.sh
![image](https://user-images.githubusercontent.com/9138402/95441382-aac46080-098c-11eb-8b61-4a8fdf6ac5d3.png)

may I ask about how to solve these issues?

**Comment by Hanjun-Dai** [comment]
Hi,

You need to use 	-comp_method "bilinear"  if you trained the model with this option.

**Comment by chontipan** [comment]
Thanks, its okay now.
