### ISSUE TITLE
No vocab files included?

### ISSUE THREAD

**Issue by HarrialX** [AI-nstein/hoppity#12]
Hi Dear Author, this is a clear and excellent implementation of your good work, which I really enjoy to read. One thing when I run the code is there is no "vocab_fixed.npy" or "vocab_full.npy", even though I direct use your provided dataset named "cooked-one-diff". Can you suggest where could I download them? @Hanjun-Dai @elizabethdinella

**Comment by elizabethdinella** [comment]
Hi, the vocab file is  `cooked-full-fmt-shift_node/vocab_fixes.npy`

**Comment by HarrialX** [comment]
@elizabethdinella Thanks! Now it could successfully run. But seems like the model takes JavaScript AST as input and output AST, are there any provided functions or APIs that could transfer the output AST back to JS programs? Or, is there any way to make these ASTs visible? (Because the AST is written by classes thus unable to print directly). Thanks!

**Comment by elizabethdinella** [comment]
For AST to source I don't have any code to do that, but you could try this: https://github.com/estools/escodegen
Although, we use SHIFT ASTs and the above tool assumes ESprima AST. So I believe you would need to do a conversion using this: https://github.com/shapesecurity/shift-spidermonkey-converter-js

You can use this to print the pkl files: https://github.com/AI-nstein/hoppity/blob/master/gtrans/data_process/depickle.py

**Comment by HarrialX** [comment]
Very appreciate for these resources! Since I'm a beginner in Javascript, seems like the SHIFT AST is different with the AST of Javascript, which cannot be parsed directly by the Python APIs that can transfer JS AST to JS code directly, are there any Python way to handle with the SHIFT AST? @elizabethdinella Thanks much!

**Comment by HarrialX** [comment]
I mean, to transfer the SHIFT AST to a Javascript program, is this process can be done by Python instead of Javascript code? 

For example, to transfer Python AST to Python program, we can simply write:
```
import ast

code = "1 + 2 * 3"
t = ast.parse(code)
print(ast.dump(t))
>>> 'Module(body=[Expr(value=BinOp(left=Constant(value=1, kind=None), op=Add(), right=BinOp(left=Constant(value=2, kind=None), op=Mult(), right=Constant(value=3, kind=None))))], type_ignores=[])'
```
However, this is using Python library to parse Python AST, can we use Python library to parse JavaScript AST and then transfer these ASTs back to JavaScript programs?

**Comment by elizabethdinella** [comment]
Unfortunately, I do not know of a python library that can parse JavaScript AST let alone SHIFT ASTs. I would recommend using JS with the resources I provided above.

**Comment by HarrialX** [comment]
ok, that's clear, thanks for such a long-tail QA
