### ISSUE TITLE
confusion about *refs.npy file and *refs2.npy in one diff dataset

### ISSUE THREAD

**Issue by chenzimin** [AI-nstein/hoppity#3]
Hi,

I have downloaded the one diff dataset and extracted it using `tar xzf cooked-one-diff.gz`. And I am trying to parse the one diff dataset.

AFAIU, you use this [generator](https://github.com/AI-nstein/hoppity/blob/1b4dc81e8e1fe914104e5fd6a700f7427c793a49/gtrans/data_process/utils.py#L30) with `file_suffix=['_buggy.pkl', '_fixed.pkl', '_gedit.txt', '_refs.npy']` (eg. at [here](https://github.com/AI-nstein/hoppity/blob/1b4dc81e8e1fe914104e5fd6a700f7427c793a49/gtrans/common/dataset.py#L251)) to generate the DataSample. However, I noticed that there are also `*refs2.npy` files in the `cooked-full-fmt-shift_node` directory extracted from `cooked-one-diff.gz`. What are the difference between `*refs.npy` and `*refs2.npy` files?

**Comment by elizabethdinella** [comment]
You can ignore `refs2.npy` sorry about the confusion! I will update the dataset shortly.
