### ISSUE TITLE
evaluation script throws error

### ISSUE THREAD

**Issue by akash-isu** [AI-nstein/hoppity#6]
when I run the eval.sh script it throws the following error. 

Traceback (most recent call last):
  File "eval.py", line 46, in <module>
    model.load_state_dict(torch.load(cmd_args.target_model, map_location=torch.device('cpu')))
  File "/Users/adutta/opt/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 829, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for GraphTrans:
	Unexpected key(s) in state_dict: "pred.main.0.weight", "pred.main.0.bias", "pred.main.2.weight", "pred.main.2.bias", "pred.main.4.weight", "pred.main.4.bias", "ops.1.pred.main.0.weight", "ops.1.pred.main.0.bias", "ops.1.pred.main.2.weight", "ops.1.pred.main.2.bias", "ops.1.pred.main.4.weight", "ops.1.pred.main.4.bias", "ops.2.pred.main.0.weight", "ops.2.pred.main.0.bias", "ops.2.pred.main.2.weight", "ops.2.pred.main.2.bias", "ops.2.pred.main.4.weight", "ops.2.pred.main.4.bias", "ops.3.pred.main.0.weight", "ops.3.pred.main.0.bias", "ops.3.pred.main.2.weight", "ops.3.pred.main.2.bias", "ops.3.pred.main.4.weight", "ops.3.pred.main.4.bias", "ops.4.pred.main.0.weight", "ops.4.pred.main.0.bias", "ops.4.pred.main.2.weight", "ops.4.pred.main.2.bias", "ops.4.pred.main.4.weight", "ops.4.pred.main.4.bias".

Is there something I'm doing wrong?

**Comment by elizabethdinella** [comment]
Hi Akash,

This error occurs when the model you trained has different hyperparameters than you are trying to load with. 
Did you change any of the parameters in the evaluation or training scripts?

Can you also take a look at this thread: https://github.com/AI-nstein/hoppity/issues/4 

- Elizabeth
