### ISSUE TITLE
best model script returns best model none

### ISSUE THREAD

**Issue by akash-isu** [AI-nstein/hoppity#7]
when I run the best model script, it returns Best Model none. Am I doing something wrong? I'm new to this field and any help would be appreciated

**Comment by elizabethdinella** [comment]
Hi, have you run the script previously? If so, change the loss file to a new file here: https://github.com/AI-nstein/hoppity/blob/master/gtrans/eval/find_best_model.sh#L6
or you can clear the contents already in the loss file you have specified. 

- Elizabeth
